import streamlit as st
import pandas as pd
import requests
from bs4 import BeautifulSoup
import tabula
from fpdf import FPDF
import plotly.express as px
from datetime import datetime

# --- CONFIG & STYLING ---
st.set_page_config(page_title="Ghana Econ-Insight Pro 2026", page_icon="🇬🇭", layout="wide")

st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    footer {visibility: hidden;}
    </style>
    """, unsafe_allow_html=True)

# --- ADVANCED DATA ENGINES ---

@st.cache_data(ttl=3600)
def fetch_advanced_market_data():
    """Fetches official and retail FX rates, plus inflation."""
    try:
        fx_url = "https://api.frankfurter.dev/v1/latest?base=USD&symbols=GHS"
        fx_data = requests.get(fx_url).json()
        official_rate = fx_data['rates']['GHS']
        # 2026 Retail/Forex Bureau spread approx 2.5%
        retail_rate = official_rate * 1.025 
    except:
        official_rate = 10.84
        retail_rate = 11.11
        
    inflation = 3.3  # Mar 2026 Targeted Rate
    return official_rate, retail_rate, inflation

def calculate_momo_fees(amt):
    """Calculates 2026 E-Levy (1.0%) and service fees."""
    e_levy = amt * 0.01
    service_fee = min(amt * 0.0075, 15.0) # Capped service fee
    return e_levy + service_fee

def initialize_paystack_test(amount_ghs, email):
    """Simulates a Paystack MoMo transaction flow."""
    PAYSTACK_SECRET = "sk_test_demo_12345" # Replace with your real key in production
    url = "https://api.paystack.co/transaction/initialize"
    headers = {"Authorization": f"Bearer {PAYSTACK_SECRET}", "Content-Type": "application/json"}
    payload = {"email": email, "amount": int(amount_ghs * 100), "currency": "GHS", "channels": ["mobile_money"]}
    try:
        res = requests.post(url, json=payload, headers=headers).json()
        return res['data']['authorization_url']
    except:
        return None

@st.cache_data
def generate_pdf_bytes(amount, interest, inflation, real_rate, usd_val, momo_fees):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(0, 107, 63) # Ghana Green
    pdf.cell(0, 10, "Advanced Investment Analysis Report", ln=True, align='C')
    pdf.ln(10)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", size=12)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d')}", ln=True)
    pdf.cell(0, 10, f"Net Investment (after MoMo fees): {amount - momo_fees:,.2f} GHS", ln=True)
    pdf.cell(0, 10, f"Annual Nominal Rate: {interest}%", ln=True)
    pdf.cell(0, 10, f"Inflation Buffer: {inflation}%", ln=True)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, f"Real Yield (Purchasing Power): {real_rate:.2f}%", ln=True)
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 5, "Confidential: Generated by Ghana Econ-Insight Pro. All financial calculations account for 2026 E-Levy and retail FX spreads.")
    return bytes(pdf.output())

# --- UI LAYOUT ---

# Sidebar
st.sidebar.header("🛠️ FinTech Settings")
amount = st.sidebar.number_input("Investment Amount (GHS)", min_value=100, value=10000, step=100)
nominal_rate = st.sidebar.slider("Nominal Annual Rate (%)", 0.0, 40.0, 15.5)

momo_total_fees = calculate_momo_fees(amount)
st.sidebar.markdown(f"**E-Levy & MoMo Fees:** {momo_total_fees:.2f} GHS")
st.sidebar.markdown(f"**Net Principal:** {(amount - momo_total_fees):,.2f} GHS")

# Data Fetching
official_fx, retail_fx, inflation_rate = fetch_advanced_market_data()

# Calculations
net_amt = amount - momo_total_fees
real_return = (((1 + (nominal_rate/100)) / (1 + (inflation_rate/100))) - 1) * 100
usd_equiv = net_amt / retail_fx

# Main Dashboard
st.title("🇬🇭 Ghana Strategic Financial Dashboard")
st.write(f"Comprehensive analysis for the 2026 economy. Current Date: **{datetime.now().strftime('%B %d, %Y')}**")

col1, col2, col3, col4 = st.columns(4)
col1.metric("Official FX (BoG)", f"{official_fx:.2f}", help="Interbank Rate")
col2.metric("Retail FX (Bureau)", f"{retail_fx:.2f}", "-0.27", help="Rate you likely pay at the counter")
col3.metric("Inflation (YoY)", f"{inflation_rate}%", "-0.1%", help="Source: Ghana Statistical Service")
col4.metric("Real Net Yield", f"{real_return:.2f}%")

st.divider()

# Advanced Analysis
c1, c2 = st.columns([2, 1])

with c1:
    st.subheader("🛡️ Portfolio Stress Test")
    devaluation = st.slider("Scenario: What if Cedi drops by (%)?", 0, 50, 15)
    scenario_rate = retail_fx * (1 + (devaluation/100))
    scenario_usd = net_amt / scenario_rate
    usd_loss = usd_equiv - scenario_usd
    
    st.error(f"In this scenario, your portfolio loses **${usd_loss:,.2f}** in global value.")
    
    # Growth Visual
    months = list(range(0, 13))
    values = [net_amt * (1 + (nominal_rate/100/12))**m for m in months]
    fig = px.area(pd.DataFrame({"Month": months, "GHS Value": values}), x="Month", y="GHS Value", 
                  color_discrete_sequence=['#fcd116'], title="Growth Projection (1 Year)")
    st.plotly_chart(fig, use_container_width=True)

with c2:
    st.subheader("💳 Digital Investment")
    u_email = st.text_input("Receipt Email", "investor@accra.com")
    if st.button("🚀 Pay with MoMo (Test Mode)"):
        pay_url = initialize_paystack_test(amount, u_email)
        if pay_url:
            st.success("Payment Link Generated!")
            st.link_button("Proceed to Paystack", pay_url)
    
    st.divider()
    
    st.subheader("📜 Export Analysis")
    pdf_data = generate_pdf_bytes(amount, nominal_rate, inflation_rate, real_return, usd_equiv, momo_total_fees)
    st.download_button(
        label="📥 Download PDF Report",
        data=pdf_data,
        file_name=f"Econ_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
        mime="application/pdf"
    )

st.divider()
st.caption("Developed by the [Your Name] | Specialized FinTech & Macro-Economic Tool | Accra 2026")
